---

- name: Install dnf release packages
  dnf: "{{ item }}"
  loop: "{{ dnf_release_packages }}"

- name: Remove minor releasever from repofiles
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '\$releasever'
    replace: "{{ releasever | split('.') | first }}"
  when: "'.' in releasever"
  loop: "{{ dnf_repofiles_no_minor_releasever }}"

- name: Install latest dnf packages
  dnf:
    name: "{{ dnf_latest_packages }}"
    state: latest

- name: Install dnf packages at specific versions
  dnf:
    name: "{{ dnf_specific_packages }}"
