---

- name: Install dnf release packages
  dnf: "{{ item }}"
  loop: "{{ dnf_release_packages }}"

- name: Install latest dnf packages
  dnf:
    name: "{{ dnf_latest_packages }}"
    state: latest

- name: Install dnf packages at specific versions
  dnf:
    name: "{{ dnf_specific_packages }}"
