- name: Install rpm keys
  ansible.builtin.rpm_key:
    key: "{{ item }}"
    state: present
  loop: "{{ rpm_keys }}"

- name: Add dnf repos
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: "/etc/yum.repos.d/{{ item.split('/')[-1] }}"
  loop: "{{ dnf_add_repos }}"

- name: Enable dnf repos
  # NB: Doesn't use `dnf config-manager --set-enabled ...` as can't make that idempotent
  lineinfile:
    path: "{{ item }}"
    create: false # raises error if not already installed
    regexp: enabled=
    line: enabled=1
  loop: "{{ dnf_enabled_repos }}"
