# modified from https://github.com/cloudalchemy/ansible-grafana/blob/master/tasks/install.yml

- name: Add Grafana repository file [RHEL/CentOS]
  template:
    src: grafana.repo.j2
    dest: "/etc/yum.repos.d/grafana.repo }}"
    force: true
    backup: true

- name: Install Grafana
  package:
    name: "{{ grafana_package }}"
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2