- name: Get builder commit
  shell:
    cmd: git describe --all --long --dirty
  register: builder_commit
  delegate_to: localhost

- name: Write builder commit to /var/lib/misc/build.txt
  copy:
    dest: /var/lib/misc/build.txt
    content: "{{ builder_commit.stdout }}"

- import_tasks: users.yml

- name: Set SELinux state and policy
  ansible.posix.selinux:
    state: "{{ selinux_state }}"
    policy: "{{ selinux_policy }}"
  register: sestatus

- name: Upgrade base image packages
  dnf:
    name: '*'
    state: latest
    exclude: "{{ dnf_update_exclude }}"
  register: dnf_upgrade

- name: Reboot if required
  reboot:
    post_reboot_delay: 30
  when: >-
    (lookup('fileglob', '/var/run/reboot-required') | length > 0) or
    ('kernel-' in dnf_upgrade.results | join) or
    (sestatus.reboot_required | default(false))

- name: Wait for hosts to be reachable
  wait_for_connection:
    sleep: 15

- import_tasks: dnf_repos.yml
- import_tasks: dnf_packages.yml
- import_tasks: prometheus.yml
- import_tasks: nodeexporter.yml
- import_tasks: grafana.yml

- name: Remove dnf caches
  command: dnf clean all

- name: Delete /etc/resolv.conf
  # required as if cloud-init (rather than network manager) controls this on next boot it won't be entirely overrwritten
  file:
    path: /etc/resolv.conf
    state: absent

- name: Delete any injected ssh config for rocky
  file:
    path: /home/rocky/.ssh/
    state: absent

- name: Run cloud-init cleanup
  command: cloud-init clean --logs --seed

# - meta: end_here # useful for debugging, can rerun
