# modified from https://github.com/cloudalchemy/ansible-prometheus/blob/400b7e010951ea6de4fdf2a835c21ab71f983c28/tasks/preflight.yml
- name: "Get checksum list"
  set_fact:
    __prometheus_checksums: "{{ lookup('url', 'https://github.com/prometheus/prometheus/releases/download/v' + prometheus_version + '/sha256sums.txt', wantlist=True) | list }}"
  
- name: "Get checksum for {{ go_arch }} architecture"
  set_fact:
    __prometheus_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ __prometheus_checksums }}"
  when:
    - "('linux-' + go_arch + '.tar.gz') in item"

# modified from https://github.com/cloudalchemy/ansible-prometheus/blob/master/tasks/install.yml
- name: Download prometheus binary
  become: false
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
    checksum: "sha256:{{ __prometheus_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: Unpack prometheus binaries
  become: false
  ansible.builtin.unarchive:
    remote_src: yes
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}/prometheus"
  check_mode: false

- name: Propagate official prometheus and promtool binaries
  ansible.builtin.copy:
    remote_src: yes
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}/{{ item }}"
    dest: "{{ _prometheus_binary_install_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
    - prometheus
    - promtool
  
- name: Propagate official console templates
  ansible.builtin.copy:
    remote_src: true
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}/{{ item }}/"
    dest: "{{ prometheus_config_dir }}/{{ item }}/"
    mode: 0644
    owner: root
    group: root
  with_items:
    - console_libraries
    - consoles
