# From ansible/bootstrap.yml

    - name: Add groups
      ansible.builtin.group: "{{ item.group }}"
      loop: "{{ appliances_local_users }}"
      when:
        - item.enable | default(true) | bool
        - "'group' in item"
      become_method: "sudo"
      # Need to change working directory otherwise we try to switch back to non-existent directory.
      become_flags: '-i'
      become: true
    - name: Add users
      ansible.builtin.user: "{{ item.user }}"
      loop: "{{ appliances_local_users }}"
      when: item.enable | default(true) | bool
      become_method: "sudo"
      # Need to change working directory otherwise we try to switch back to non-existent directory.
      become_flags: '-i'
      become: true
    - name: Reset ssh connection to allow user changes to affect ansible_user
      meta: reset_connection
