go_arch: amd64 

# https://github.com/cloudalchemy/ansible-prometheus/blob/master/defaults/main.yml
prometheus_version: 2.27.0
prometheus_config_dir: /etc/prometheus

# https://github.com/cloudalchemy/ansible-prometheus/blob/master/vars/main.yml
_prometheus_binary_install_dir: '/usr/local/bin'

# https://github.com/cloudalchemy/ansible-node-exporter/blob/master/defaults/main.yml
node_exporter_version: 1.1.2
_node_exporter_binary_install_dir: "/usr/local/bin"

# https://github.com/cloudalchemy/ansible-grafana/blob/master/defaults/main.yml
grafana_version: latest

# https://github.com/cloudalchemy/ansible-grafana/blob/master/vars/redhat.yml
grafana_package: "grafana{{ (grafana_version != 'latest') | ternary('-' ~ grafana_version, '') }}"
