rpm_keys:
  - https://yum.osc.edu/ondemand/RPM-GPG-KEY-ondemand # https://github.com/OSC/ood-ansible/blob/master/defaults/main/install.yml: rpm_repo_key

dnf_add_repos: # list of .repo URLs
  - https://turbovnc.org/pmwiki/uploads/Downloads/TurboVNC.repo

dnf_enabled_repos: # list of .repo paths
  - /etc/yum.repos.d/Rocky-PowerTools.repo

dnf_release_packages: # list of ansible.builtin.dnf args for packages to install before attempting other package installs
  - name: epel-release.noarch
  - name: http://repos.openhpc.community/OpenHPC/2/CentOS_8/x86_64/ohpc-release-2-1.el8.x86_64.rpm # https://github.com/stackhpc/ansible-role-openhpc/blob/master/tasks/install.yml
    disable_gpg_check: yes
  - name: https://yum.osc.edu/ondemand/2.0/ondemand-release-web-2.0-1.noarch.rpm # https://github.com/OSC/ood-ansible/blob/master/defaults/main/install.yml:rpm_repo_url
    disable_gpg_check: yes

dnf_latest_packages: # list of packages to install using dnf
  
  # https://github.com/stackhpc/ansible-role-openhpc/blob/master/vars/ohpc-2
  # control:
  - "ohpc-slurm-server"
  - "slurm-slurmctld-ohpc"
  - "slurm-example-configs-ohpc"
  # batch:
  - "ohpc-base-compute"
  - "ohpc-slurm-client"
  # runtime:
  - "slurm-ohpc"
  - "munge"
  - "slurm-slurmd-ohpc"
  - "slurm-example-configs-ohpc"
  - "lmod-ohpc"
  # database:
  - "slurm-slurmdbd-ohpc"

  # https://github.com/stackhpc/ansible-slurm-appliance/blob/main/environments/common/inventory/group_vars/all/openhpc.yml
  - slurm-libpmi-ohpc
  - ohpc-gnu9-openmpi4-perf-tools
  - openblas-gnu9-ohpc

  # https://github.com/OSC/ood-ansible/blob/master/vars/Rocky.yml
  - lua-posix

  # https://github.com/stackhpc/ansible-role-cluster-nfs/blob/master/tasks/main.yml
  - nfs-utils

  # https://github.com/stackhpc/ansible-slurm-appliance/blob/main/ansible/roles/podman/tasks/prereqs.yml
  - podman
  - python3

  # https://github.com/stackhpc/ansible-slurm-appliance/blob/main/ansible/roles/openondemand/tasks/vnc_compute.yml
  - nmap-ncat
  - '@Xfce'

  # https://github.com/cloudalchemy/ansible-grafana/blob/master/vars/redhat.yml
  - chkconfig

dnf_specific_packages:
  # done separately as @ruby and @nodejs are el8.4 modules which breaks if requiring latest, as for above
  # https://github.com/OSC/ood-ansible/blob/master/vars/Rocky.yml
  - '@ruby:2.7'
  - '@nodejs:12'
  
  # https://github.com/stackhpc/ansible-slurm-appliance/blob/main/ansible/roles/openondemand/tasks/vnc_compute.yml
  - turbovnc-2.2.7
  
  # https://github.com/OSC/ood-ansible/blob/master/tasks/install-rpm.yml
  - ondemand

  # NB: firewalld can't be installed in this image as it starts on boot, which is not wanted

dnf_update_exclude: omit
