
prometheus_db_dir: /var/lib/prometheus # will get moved to appliances state dir by appliance

# from environments/common/inventory/group_vars/all/defaults.yml:

appliances_local_users_ansible_user_name: "{{ ansible_ssh_user | default(ansible_user) }}"
appliances_local_users_podman: # also used in environments/common/inventory/group_vars/all/podman.yml:podman_users
    name: podman
    comment: Used for running all containers
    # Would like to set subuid so that we that we know what will appear in /etc/subuid
    # See: https://github.com/ansible/ansible/issues/68199
    home: /var/lib/podman
    uid: 1001

appliances_local_users_default:
    - user:
        name: "{{ appliances_local_users_ansible_user_name }}"
        home: /var/lib/{{ appliances_local_users_ansible_user_name }}
        move_home: true
        local: true
    
    - user: "{{ appliances_local_users_podman }}"
      enable: true # "{{ 'podman' in group_names }}"

    - user:
        name: slurm
        comment: SLURM resource manager
        home: /etc/slurm
        shell: /sbin/nologin
        uid: 202
        system: true
      enable: true # "{{ 'control' in group_names }}"
    
    - group:
        name: prometheus
        gid: 976
      user:
        name: prometheus
        uid: 981
        home: "{{ prometheus_db_dir }}"
        shell: /usr/sbin/nologin
      enable: true # "{{ 'prometheus' in group_names }}"
    
    - group:
        name: grafana
        gid: 979
      user:
        name: grafana
        comment: grafana user
        uid: 984
        home: /usr/share/grafana
        shell: /sbin/nologin
      enable: true # "{{ 'grafana' in group_names }}"

# Overide this to add extra users whilst keeping the defaults.
appliances_local_users_extra: [] # see format of appliances_local_users_default above
appliances_local_users: "{{ appliances_local_users_default + appliances_local_users_extra }}"
