# Download the last image built by packer
- hosts: localhost
  become: no
  gather_facts: no
  tasks:
    - name: Read packer build manifest
      set_fact:
        manifest: "{{ lookup('file', manifest_path) | from_json }}"
      vars:
        manifest_path: ../packer-manifest.json
      changed_when: false

    - name: Get openstack info for image
      shell:
        cmd: "openstack image show --format json {{ last_build.artifact_id }}"
      register: image
      vars:
        last_build: "{{ manifest['builds'] | last }}"
      changed_when: false
    
    - name: Download last image
      shell:
        cmd: "openstack image save --file ~/{{image_name }} {{ last_build.artifact_id }}"
        creates: "{{ image_name }}"
      vars:
        last_build: "{{ manifest['builds'] | last }}"
        image_name: "{{ (image.stdout | from_json).name }}"
    