name: Build images on arcus:rcp-cloud-portal-demo
on:
  push:
    branches:
      - main
  pull_request:
concurrency: rcp-cloud-portal-demo # openstack project
jobs:
  arcus:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./collections/ansible_collections/stackhpc/slurm_image_builder
    steps:
      - uses: actions/checkout@v2
        with:
          path: collections/ansible_collections/stackhpc/slurm_image_builder

      - name: Setup ssh
        run: |
          set -x
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
        env:
          SSH_KEY: ${{ secrets.ARCUS_SSH_KEY }}

      - name: Add bastion's ssh key to known_hosts
        run: cat .github/arcus_bastion_fingerprint >> ~/.ssh/known_hosts
        shell: bash
      
      - name: Install ansible etc
        run: ./setup.sh

      - name: Write clouds.yaml
        run: |
          mkdir -p ~/.config/openstack/
          echo "$CLOUDS_YAML" > ~/.config/openstack/clouds.yaml
        shell: bash
        env:
          CLOUDS_YAML: ${{ secrets.ARCUS_CLOUDS_YAML }}
      
      - name: Run image build
        # NB: assumes port and security groups exist - could improve/use main.tf
        id: image_build
        run: |
          . venv/bin/activate
          PACKER_LOG=1 packer build --on-error=ask -var-file=arcus.builder.pkrvars.hcl openstack.pkr.hcl
        env:
          OS_CLOUD: openstack
