name: Build images on smslabs:stackhpc-ci
on:
  push:
    branches:
      - main
  pull_request:
concurrency: stackhpc-ci # openstack project
jobs:
  smslabs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup ssh
        run: |
          set -x
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}

      - name: Add bastion's ssh key to known_hosts
        run: cat .github/smslabs_bastion_fingerprint >> ~/.ssh/known_hosts
        shell: bash
      
      - name: Install ansible etc
        run: ./setup.sh

      - name: Write clouds.yaml
        run: |
          mkdir -p ~/.config/openstack/
          echo "$CLOUDS_YAML" > ~/.config/openstack/clouds.yaml
        shell: bash
        env:
          CLOUDS_YAML: ${{ secrets.CLOUDS_YAML }}
      
      - name: Run image build
        id: image_build
        run: |
          . venv/bin/activate
          PACKER_LOG=1 packer build --on-error=ask -var-file=smslabs.builder.pkrvars.hcl openstack.pkr.hcl
        env:
          OS_CLOUD: openstack
      
      - name: Download image
        run: |
          . venv/bin/activate
          ansible-playbook playbooks/download_image.yml 
        env:
          OS_CLOUD: openstack
      
      - name: Upload image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: latest-image
          path: ~/*.qcow2
        
